//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Aguiñagalde.WebServices.InfoCred {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="InfoCredServicesBinding", Namespace="http://localhost/infocred/modules/webservice")]
    public partial class InfoCredServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback consultaFichaPFN1OperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaFichaPJOperationCompleted;
        
        private System.Threading.SendOrPostCallback listadoConsultasResumidoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public InfoCredServices() {
            this.Url = global::Aguiñagalde.WebServices.Properties.Settings.Default.WebServices_InfoCred_InfoCredServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event consultaFichaPFN1CompletedEventHandler consultaFichaPFN1Completed;
        
        /// <remarks/>
        public event consultaFichaPJCompletedEventHandler consultaFichaPJCompleted;
        
        /// <remarks/>
        public event listadoConsultasResumidoCompletedEventHandler listadoConsultasResumidoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://www.infocred.com.uy/infocred/modules/webservice/index.php/consultaFichaPF" +
            "N1", RequestNamespace="http://localhost/infocred/modules/webservice", ResponseNamespace="http://localhost/infocred/modules/webservice")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string consultaFichaPFN1(string usuario, string clave, string tipo_id, string nro_id) {
            object[] results = this.Invoke("consultaFichaPFN1", new object[] {
                        usuario,
                        clave,
                        tipo_id,
                        nro_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultaFichaPFN1Async(string usuario, string clave, string tipo_id, string nro_id) {
            this.consultaFichaPFN1Async(usuario, clave, tipo_id, nro_id, null);
        }
        
        /// <remarks/>
        public void consultaFichaPFN1Async(string usuario, string clave, string tipo_id, string nro_id, object userState) {
            if ((this.consultaFichaPFN1OperationCompleted == null)) {
                this.consultaFichaPFN1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaFichaPFN1OperationCompleted);
            }
            this.InvokeAsync("consultaFichaPFN1", new object[] {
                        usuario,
                        clave,
                        tipo_id,
                        nro_id}, this.consultaFichaPFN1OperationCompleted, userState);
        }
        
        private void OnconsultaFichaPFN1OperationCompleted(object arg) {
            if ((this.consultaFichaPFN1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaFichaPFN1Completed(this, new consultaFichaPFN1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://www.infocred.com.uy/infocred/modules/webservice/index.php/consultaFichaPJ" +
            "", RequestNamespace="http://localhost/infocred/modules/webservice", ResponseNamespace="http://localhost/infocred/modules/webservice")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string consultaFichaPJ(string usuario, string clave, string tipo_id, string nro_id) {
            object[] results = this.Invoke("consultaFichaPJ", new object[] {
                        usuario,
                        clave,
                        tipo_id,
                        nro_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultaFichaPJAsync(string usuario, string clave, string tipo_id, string nro_id) {
            this.consultaFichaPJAsync(usuario, clave, tipo_id, nro_id, null);
        }
        
        /// <remarks/>
        public void consultaFichaPJAsync(string usuario, string clave, string tipo_id, string nro_id, object userState) {
            if ((this.consultaFichaPJOperationCompleted == null)) {
                this.consultaFichaPJOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaFichaPJOperationCompleted);
            }
            this.InvokeAsync("consultaFichaPJ", new object[] {
                        usuario,
                        clave,
                        tipo_id,
                        nro_id}, this.consultaFichaPJOperationCompleted, userState);
        }
        
        private void OnconsultaFichaPJOperationCompleted(object arg) {
            if ((this.consultaFichaPJCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaFichaPJCompleted(this, new consultaFichaPJCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://www.infocred.com.uy/infocred/modules/webservice/index.php/listadoConsulta" +
            "sResumido", RequestNamespace="http://localhost/infocred/modules/webservice", ResponseNamespace="http://localhost/infocred/modules/webservice")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string listadoConsultasResumido(string usuario, string clave, string fecha_desde, string fecha_hasta, string cod_cci, string nro_empresa_desde, string nro_empresa_hasta) {
            object[] results = this.Invoke("listadoConsultasResumido", new object[] {
                        usuario,
                        clave,
                        fecha_desde,
                        fecha_hasta,
                        cod_cci,
                        nro_empresa_desde,
                        nro_empresa_hasta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void listadoConsultasResumidoAsync(string usuario, string clave, string fecha_desde, string fecha_hasta, string cod_cci, string nro_empresa_desde, string nro_empresa_hasta) {
            this.listadoConsultasResumidoAsync(usuario, clave, fecha_desde, fecha_hasta, cod_cci, nro_empresa_desde, nro_empresa_hasta, null);
        }
        
        /// <remarks/>
        public void listadoConsultasResumidoAsync(string usuario, string clave, string fecha_desde, string fecha_hasta, string cod_cci, string nro_empresa_desde, string nro_empresa_hasta, object userState) {
            if ((this.listadoConsultasResumidoOperationCompleted == null)) {
                this.listadoConsultasResumidoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistadoConsultasResumidoOperationCompleted);
            }
            this.InvokeAsync("listadoConsultasResumido", new object[] {
                        usuario,
                        clave,
                        fecha_desde,
                        fecha_hasta,
                        cod_cci,
                        nro_empresa_desde,
                        nro_empresa_hasta}, this.listadoConsultasResumidoOperationCompleted, userState);
        }
        
        private void OnlistadoConsultasResumidoOperationCompleted(object arg) {
            if ((this.listadoConsultasResumidoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listadoConsultasResumidoCompleted(this, new listadoConsultasResumidoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void consultaFichaPFN1CompletedEventHandler(object sender, consultaFichaPFN1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaFichaPFN1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaFichaPFN1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void consultaFichaPJCompletedEventHandler(object sender, consultaFichaPJCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaFichaPJCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaFichaPJCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void listadoConsultasResumidoCompletedEventHandler(object sender, listadoConsultasResumidoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listadoConsultasResumidoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listadoConsultasResumidoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591